---
- name: Gather System Information
  hosts: ubuntu
  become: true  # Run tasks with sudo

  tasks:
    - name: Get System Facts
      ansible.builtin.setup:

    - name: Display System Facts
      debug:
        var: ansible_facts

    - name: Check System Health (Example: Check if a process is running)
      ansible.builtin.systemd:
        name: your_process_name
      register: process_status

    - name: Display Process Status
      debug:
        var: process_status

    - name: Get RAM and Disk Usage
      ansible.builtin.shell: |
        free -m
        df -h
      register: usage_output

    - name: Display RAM and Disk Usage
      debug:
        var: usage_output.stdout_lines
