---
- name: Use Environment Variable in Ansible Playbook
  hosts: ubuntu
  vars:
    my_variable: "{{ lookup('env', 'key') }}"

  tasks:
    - name: Display the value of the environment variable
      debug:
        msg: "The value of MY_ENV_VARIABLE is {{ my_variable | default('not set') }}"
