---
- name: Update system
  hosts: your_target_hosts
  become: yes
  become_method: sudo

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
