---
- name: Gather System Facts without Root Access
  hosts: ubuntu
  gather_facts: true
  become: yes
  become_user: your_non_root_user

  tasks:
    - name: Display System Facts
      debug:
        var: ansible_facts
