---
- name: Basic Task Without Sudo
  hosts: ubuntu
  gather_facts: false  # Disable gathering facts

  tasks:
    - name: Create Directory
      file:
        path: /home
        state: directory
      become: no  # Do not attempt to become another user

    - name: Create File
      file:
        path: /home/your_file.txt
        state: touch
      become: no  # Do not attempt to become another user
