---
- name: Update Ubuntu Packages
  hosts: your_ubuntu_servers
  become: true
  become_method: sudo
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
