---
- name: Update Ubuntu System
  hosts: your_ubuntu_hosts
  become: yes
  become_user: root

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
